program: ./src/main.cpp ./src/particles.cpp ./src/config.cpp ./src/mouse.cpp ./headers/def.hpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
	g++ -O3 ./src/main.cpp ./src/particles.cpp ./src/config.cpp  ./src/mouse.cpp ./headers/def.hpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o main
